data:
  random_state: 42
  raw_path: data/heart_disease.csv
  target_col: target
  test_size: 0.2
mlflow:
  experiment_name: Heart_Disease_Classifier
  tracking_uri: sqlite:///mlflow.db
model:
  max_depth: 4
  min_accuracy_threshold: 0.7
  n_estimators: 80
  random_state: 42
  type: RandomForestClassifier
preprocessing:
  categorical_cols:
  - sex
  - cp
  - fbs
  - restecg
  - exang
  - slope
  - ca
  - thal
  impute_strategy: median
  numeric_cols:
  - age
  - trestbps
  - chol
  - thalach
  - oldpeak
